### ISSUE TITLE
Error Login to Private Registry 2.0

### ISSUE THREAD

**Issue by StrongPa55word** [docker/docker-registry#1013]
[root@ip-10-95-0-197 conf.d]docker login ***.com
Username: admin
Password: 
Email: 
FATA[0006] Error response from daemon: (Code: 404; Headers: map[Content-Type:[text/plain; charset=utf-8] Date:[Wed, 17 Jun 2015 17:30:59 GMT] Docker-Distribution-Api-Version:[registry/2.0] Content-Length:[19] Connection:[keep-alive]]) 
FATA[0006] Error response from daemon: (Code: 404; Headers: map[Content-Type:[text/plain; charset=utf-8] Date:[Wed, 17 Jun 2015 17:30:59 GMT] Docker-Distribution-Api-Version:[registry/2.0] Content-Length:[19] Connection:[keep-alive]])

**Comment by dmp42** [comment]
I assume you are using the new registry.
This repository here is about the deprecated, python registry, as advertised in the readme and project description.

Have you followed the documentation?

Specifically:
- https://github.com/docker/distribution/blob/master/docs/deploying.md
- https://github.com/docker/distribution/blob/master/docs/authentication.md

Also, the information you provide is insufficient to help you.

You can find out more here: https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

I would suggest to review these first, then if you still have a problem, ask for help on irc (#docker-distribution) or the support forums, and if there is still a problem, open an issue on https://github.com/docker/distribution
