### ISSUE TITLE
Editing webhook: cannot update Short Name

### ISSUE THREAD

**Issue by richburdon** [docker/docker-registry#1025]
Repro:
- https://registry.hub.docker.com/u/XXX/YYY/settings/webhooks/
- Click Edit
- Change short name
- Click Save

Name doesn't change.

**Comment by dmp42** [comment]
Hi, 

Hub issues should be reported to https://support.docker.com/

This repository here is about the (deprecated) open-source registry, and is unrelated to your issue.
