### ISSUE TITLE
Issues connecting: port 5000: Connection refused

### ISSUE THREAD

**Issue by krinkere** [docker/docker-registry#1028]
Docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Steps:
1. Run 
$ docker-machine create --driver virtualbox --engine-insecure-registry 192.168.99.100:5000 dev

where 192.168.99.100 is my docker's machine IP
$ docker-machine ls
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM
dev           \*        virtualbox   Running   tcp://192.168.99.100:2376   
1. Set up docker
   docker-machine env dev
   eval "$(docker-machine env dev)"
2. Try to reach registry via curl and it fails to connect
   $ curl http://192.168.99.100:5000/v1/_ping
   curl: (7) Failed to connect to 192.168.99.100 port 5000: Connection refused

Thought adding --engine-insecure-registry would take care of it according to the documentation?

**Comment by dmp42** [comment]
`--engine-insecure-registry` does not install a registry.
You may start here to install one: https://github.com/docker/distribution/blob/master/docs/index.md

**Comment by krinkere** [comment]
I did install it...
I was able to resolve the issue by shutting everything down and recreating everything from scratch. Perhaps something went wrong the very first time when I was setting up... but yeah, not an issue.
