### ISSUE TITLE
docker search returns 404

### ISSUE THREAD

**Issue by dmilltech** [docker/docker-registry#1029]
docker search <hostname>:5000/centos
Error response from daemon: Unexpected status code 404

curl -k -s -X GET https://<username>@<hostname>:5000/v2/centos/tags/list
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"repository","Name":"centos","Action":"pull"}]}]}

**Comment by stevvooe** [comment]
This is a duplicated of docker/distribution#975.
