### ISSUE TITLE
registry:2.2.0 receives a push with one ID and then returns a new id when pulled

### ISSUE THREAD

**Issue by RandyAbernethy** [docker/docker-registry#1037]
Example below shows image 876e7da31048 changing to 6c56085c56b6 when pulled with v1.9.0

user@ubuntu:~$ docker push localhost:5000/devenv
The push refers to a repository [localhost:5000/devenv](len: 1)
876e7da31048: Pushed 
1d073211c498: Pushed 
5a4526e952f0: Pushed 
99fcaefe76ef: Pushed 
c63fb41c2213: Pushed 
latest: digest: sha256:7d263d2c98f8e79a6b6cb4fa88f181ecb906b5a822bf37ed7cae3de3d7251d69 size: 8977

user@ubuntu:~$ docker rmi localhost:5000/devenv
Untagged: localhost:5000/devenv:latest
Deleted: 876e7da3104878eb1ee33f5319b67a9bd8b7653bebd95003babcd7484f9254dc

user@ubuntu:~$ docker pull localhost:5000/devenv
Using default tag: latest
latest: Pulling from devenv
6c56085c56b6: Pull complete 
Digest: sha256:7d263d2c98f8e79a6b6cb4fa88f181ecb906b5a822bf37ed7cae3de3d7251d69
Status: Downloaded newer image for localhost:5000/devenv:latest

**Comment by dmp42** [comment]
This here is the python registry, which is deprecated.
Can I ask that you head over to https://github.com/docker/distribution?

Thanks.

**Comment by RandyAbernethy** [comment]
thanks for the redirect sorry for the noise...
