### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by darint00** [docker/docker-registry#1045]
I've seen other issues about this.  Let me explain what I need to do.  We have a repository that was named too specific.  Now we have an updated docker image that name doesn't apply.  We want to push the update image, but maintain the stars/downloads metadata information.  This is the use case we have in "renaming" the current docker hub repository.  So we can maintain that information, and then push the updated docker image.

**Comment by dmp42** [comment]
For Docker Hub issues, you should contact https://support.docker.com

This here is the open-source registry (and it's the deprecated version - the current version lives in docker/distribution).
