### ISSUE TITLE
What is the correct storage directory for the images stored in registry (v2)? (For persistent storage)

### ISSUE THREAD

**Issue by KamranAzeem** [docker/docker-registry#1058]
Hi,
On the documentation page of Registry on Docker Hub, https://hub.docker.com/_/registry/ , I see: 

Run registry (quick version):
"..... -v <HOST_DIR>:/tmp/registry-dev registry"

Recommended: Run registry:
" $ docker run \
         -e SETTINGS_FLAVOR=s3 \
         -e AWS_BUCKET=acme-docker \
         -e STORAGE_PATH=/registry \
......"

issue-1: Which one is the correct place to volume mount a host directory for persistent storage? 
issue-2: What is the location for image storage in Registry v2? The document is silent about it.

Thanks!

**Comment by asbjornenge** [comment]
This is very confusing for me also.

**Comment by dmp42** [comment]
Please disregard https://hub.docker.com/_/registry/ and also this repository here, which is flagged "deprecated" (https://github.com/docker/docker-registry)

Following the documentation https://docs.docker.com/registry/overview/ should get you started.
