### ISSUE TITLE
docker push‘ Error pushing to registry: Server error: 400 trying to push xxxx blob - sha256: .'

### ISSUE THREAD

**Issue by zhangdakun** [docker/docker-registry#1061]
after i push a image to my private docker registry
I go a error msg , Error pushing to registry: Server error: 400 trying to push xxxx blob - sha256: .'
so I try to push again and again, 
about 3 times retry ,it shows pushed

but after I try to pull this image ,it cause docker crashed

docker pull  xxx
cb1c5c58bb5e: Already exists 
 not foundpull repository  xxx

vim /var/log/message

 docker: syscall.Read(0x2c, 0xc208464000, 0x8000, 0x8000, 0xa5a780, 0x0, 0x0)
 docker: /usr/lib/golang/src/syscall/syscall_unix.go:136 +0x58 fp=0xc20865d5f0 sp=0xc20865d5b0
docker: os.(*File).read(0xc2084a4cb0, 0xc208464000, 0x8000, 0x8000, 0xc208464000, 0x0, 0x0)
docker: /usr/lib/golang/src/os/file_unix.go:191 +0x5e fp=0xc20865d630 sp=0xc20865d5f0
systemd: docker.service: main process exited, code=killed, status=6/ABRT

docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-108.el7.centos.x86_64
Go version (client): go1.4.2
Git commit (client): 3043001/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-108.el7.centos.x86_64
Go version (server): go1.4.2
Git commit (server): 3043001/1.7.1
OS/Arch (server): linux/amd64

**Comment by dmp42** [comment]
I really suggest upgrading to a more recent docker version (1.10 was released recently), as it's quite likely your bug has been fixed by one of these.

Also saying what registry version you are running, your registry logs and config, along with your docker daemon logs (preferably in debug) will be necessary to debug this.

**Comment by zhangdakun** [comment]
upgrade docker daemon ，then not crashed so closed
