### ISSUE TITLE
trusted registry: push on wrong port

### ISSUE THREAD

**Issue by vpusher** [docker/docker-registry#1063]
I have just installed a docker Trusted Registry on premise server and having some trouble to push on it.

I configured **Domain name** = `domain.com`, **HTTP Port** = `5000`,  **HTTPS port** = `5043`. I also configured my client to trust _domain.com_ certificate. Accessing through the web UI at `https:domain.com:5043` is ok.

However, I'm not not able to push

``` bash
$ docker login https://domain.com:5043
Username (admin): admin
Password: 
Email: 
WARNING: login credentials saved in /Users/vpusher/.docker/config.json
Login Succeeded
```

``` bash
$ docker tag nginx domain.com:5043/admin/nginx
$ docker push domain.com:5043/admin/nginx
1a908c5b60b5: Pushing 1.024 kB
dial tcp 10.235.64.84:443: connection refused
```

Docker 1.9 both client and server.
Docker Trusted Registry 1.4.2.

Why docker is initing the connection on port 443 instead of 5043 ? There is no service listening 443 on _domain.com_.
Is that related to the Docker registry ?

**Comment by vpusher** [comment]
A little more precisions:

First, I get the `authentication required` error:

```
$ docker push domain.com:5043/admin/nginx
The push refers to a repository [domain.com:5043/admin/nginx] (len: 1)
1a908c5b60b5: Preparing 
unauthorized: authentication required
```

Then, I create the repository through the UI, and I finally get the `connection refused` error:

```
$ docker push domain.com:5043/admin/nginx
The push refers to a repository [domain.com:5043/admin/nginx] (len: 1)
1a908c5b60b5: Pushing 1.024 kB
dial tcp 10.235.64.84:443: connection refused
```

**Comment by dmp42** [comment]
Hi, DTR is a commercial product, with dedicated support.
I encourage you to reach out to them to get help ASAP.
You can certainly start with support@docker.com

Furthemore, non-default ports bug in DTR is known, though it's really a DTR-only issue (and not upstream open-source), hence there is unfortunately nothing we can do here.

I'm going to close this for book-keeping, but please mention this ticket in your mail to support.

Hope that helps.
