### ISSUE TITLE
registry - image exists - but doesn't show in catalog

### ISSUE THREAD

**Issue by goatherder** [docker/docker-registry#1103]
I have a private docker-registry (registry:2) - using S3 storage & redis blobdescriptor cache.  

I've recently pushed a new image (<host>/prefix/image:2.2.0) -  but it doesn't show up in the catalog (`curl -XGET <address>/v2/_catalog`... other images show, including new images pushed afterwards)... 

However, I am able to pull the image, see it in the redis cache (KEYS /prefix/image* & DUMP), see it on the S3 storage (s3://bucket/docker/registry/v2/repositories/prefix/image/) and list it's tags (`curl -XGET <address>/v2/<image>/tags/list`)..  etc...   

Anyone know why an image wouldn't show up in the catalog, but work for all other operations?

**Comment by jfchevrette** [comment]
@goatherder I'm having the same issue. Were you able to fix it?

**Comment by goatherder** [comment]
Yes, this was an embarrassing one - pagination.  I just needed to append ?n=<number of images per page>&last=<last image in previous listing>
