### ISSUE TITLE
Use Nexus / Artifactory

### ISSUE THREAD

**Issue by coderlol** [docker/docker-registry#168]
Any plan to use Nexus or Artifactory (Java maven Repo systems) as the registry?  Why invent yet another registry model?

The Maven repo model and architecture are quite flexible and powerful.

**Comment by dkirrane** [comment]
Artifactory JIRA: (Pro version now supports this)
https://www.jfrog.com/jira/browse/RTFACT-6494

Nexus JIRA:
https://issues.sonatype.org/browse/NEXUS-8242
