### ISSUE TITLE
possible to make http HEAD request to a registry to verify the image exists?

### ISSUE THREAD

**Issue by scivm** [docker/docker-registry#202]
Hi,

Is it possible to make http HEAD request to a registry to verify the image exists before trying to download it with a docker pull?  

I see this structure in the data directory registry/repositories/library/<image-name>  but not sure if it callable since I don't have deep understanding of how the registry works.

I have an API server that should make sure that the image exists prior to launching a docker cluster on multiple hosts that will pull the image.  Pulling the entire image just to verify it exists would be too expensive.

Thanks,
Mike

**Comment by elharo** [comment]
This would be a violation of HTTP. Per the HTTP 1.1 spec:

"The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response (i.e., the response terminates at
   the end of the header section). "
