### ISSUE TITLE
Local registry don't have instruction on how to activate local account

### ISSUE THREAD

**Issue by rockyfaninus** [docker/docker-registry#210]
I setup a local docker-registry and run docker run -d -p 5000:5000 registry, it start up no problem. 
When I push a image to localhost:5000/ubuntu/ping, I was been asked user name and password, email. Then I got these message:

Account created. Please see the documentation of the registry http://localhost:5000/v1/ for instructions how to activate it.

The problem is: http://localhost:5000/v1 does not existing. I have no instruction on how to continue.

When push image, I got error: Error: Status 403 trying to push repository ubuntu/ping: "Access denied, you don't have access to this repo"

I tried with standalone:true in configure file, it is same.

FYI: I didnot get email too. Don't know how the registry localhost handling the email.

Anything else need to do in order to local registry access local user?

Thanks.

**Comment by saurabhtandon13** [comment]
whenever there is an error
 FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get https://registry.access.redhat.com/v1/_ping: dial tcp: lookup registry.access.redhat.com: no such host. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.access.redhat.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.access.redhat.com/ca.crt

solution to this is creation of account using the docker 

# docker login registry.access.redhat.com ( complete the details like username, password , email address) after sometime account will be created and message will be get display.

login to the server using the account created 
 # docker login < user_name>

and run the docker pull command to download the registry from redhat.

**Comment by SadiqueManzar** [comment]
Didnot worked. Adding --insecure-registry
