### ISSUE TITLE
Invalid Registry endpoint - dial tcp: i/o timeout

### ISSUE THREAD

**Issue by dlewanda** [docker/docker-registry#286]
I have a private registry running on a remote server behind nginx for authentication using S3 as the backend that had been working fine until recently. I am now getting more-than-occasional issues when trying to login or push or pull remotely. I get the following error:

Error: auth: Invalid Registry endpoint: Get https://<my-server-name>/v1/_ping: dial tcp: i/o timeout

It happened from one computer first but not the other, but now both computers on 2 separate WAN connections are suffering the same problem. If I try to run my docker login command from the machine hosting the registry (but still using the DNS name for the machine to allow my certificates to work), it works fine. Remotely, I can use curl with the expected username and password to get a proper response: "docker-registry server (dev)"

Any ideas?

**Comment by serbrech** [comment]
I experienced the same thing on OS X Yosemite. 
It was failing with  

    FATA[0032] Post https://<IP address>:2376/v1.16/images/my-image/push?tag=: dial tcp <IP address>:2376: i/o timeout  

Running `boot2docker restart` did the trick.

**Comment by SamSaffron** [comment]
just re-confirming this, if for any reason your primary dns goes down and you start running on secondary, expect this failure. 

I do think its a client bug, however easily fixable

**Comment by nickdgriffin** [comment]
@SamSaffron I've just come across a similar issue where /etc/resolv.conf container two nameserver entries where the first does not exist - docker gives an i/o timeout as it doesn't appear to consider the second nameserver at all, yet curl will. If the first/only nameserver in /etc/resolv.conf is the correct working DNS server then docker works just fine. I'm wondering if this is another netgo issue, but I can't find any related issues for it and it's probably worth testing against Go 1.5 anyway.
