### ISSUE TITLE
HTTP code 401 while uploading metadata: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Telmo** [docker/docker-registry#298]
Hello,

disclaimer:IPs and fqdns have been obscured to protect the non so innocent.

I am using the docker-registry rpm from the EPEL repo in a CentOS 6.5 system configured with local storage and going through nginx proxy (using the config found on this repo with some minor changes). When I try to push an image I keep getting:

``` sh
core@localhost ~ $ docker push docker-indexer.my.own.network.net/foreman
The push refers to a repository [docker-indexer.my.own.network.net/foreman] (len: 1)
Sending image list
Pushing repository docker-indexer.my.own.network.net/foreman (1 tags)
511136ea3c5a: Pushing
2014/03/25 15:31:52 push: HTTP code 401 while uploading metadata: invalid character '<' looking for beginning of value
```

Even thought the log level is set to debug I get no more information on the logfiles that if I were to set it to something else.. my config looks like this:

``` yaml
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    secret_key: my private key
    standalone: true
    cache:
        host: localhost
        port: 6379
        db: 0

# This is the default configuration when no flavor is specified
dev:
    storage: local
    storage_path: /app/indexer/images/
    loglevel: debug

# To specify another flavor, set the environment variable SETTINGS_FLAVOR
# $ export SETTINGS_FLAVOR=prod
prod:
    storage: local
    storage_path: /app/indexer/images/

# This flavor is automatically used by unit tests
test:
    storage: local
    storage_path: /app/indexer/images/

local:
    storage: local
    storage_path: /app/indexer/images/
```

The docker-registry log doesn't offer much info

```
127.0.0.1 - - [25/Mar/2014:15:40:25] "GET /v1/_ping HTTP/1.0" 200 4 "-" "Go 1.1 package http"
INFO:gunicorn.access:127.0.0.1 - - [25/Mar/2014:15:40:25] "GET /v1/_ping HTTP/1.0" 200 4 "-" "Go 1.1 package http"
127.0.0.1 - - [25/Mar/2014:15:40:31] "GET /v1/_ping HTTP/1.0" 200 4 "-" "Go 1.1 package http"
INFO:gunicorn.access:127.0.0.1 - - [25/Mar/2014:15:40:31] "GET /v1/_ping HTTP/1.0" 200 4 "-" "Go 1.1 package http"
127.0.0.1 - - [25/Mar/2014:15:40:31] "PUT /v1/repositories/foreman/ HTTP/1.0" 200 2 "-" "docker/0.8.1 go/go1.2 git-commit/a1598d1 kernel/3.13.5+ os/linux arch/amd64"
INFO:gunicorn.access:127.0.0.1 - - [25/Mar/2014:15:40:31] "PUT /v1/repositories/foreman/ HTTP/1.0" 200 2 "-" "docker/0.8.1 go/go1.2 git-commit/a1598d1 kernel/3.13.5+ os/linux arch/amd64"
```

The nginx log error file shows a connection refused even though the server is responding

```
==> docker-registry.access.log <==
192.192.192.192 - - [25/Mar/2014:15:42:17 +0000] "GET /v1/_ping HTTP/1.1" 200 4 "-" "Go 1.1 package http" "-"
192.192.192.192 - - [25/Mar/2014:15:42:22 +0000] "GET /v1/_ping HTTP/1.1" 200 4 "-" "Go 1.1 package http" "-"

==> docker-registry.error.log <==
2014/03/25 15:42:22 [error] 29448#0: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 192.192.192.192, server: docker-indexer.my.own.network.net, request: "PUT /v1/repositories/foreman/ HTTP/1.1", upstream: "http://[::1]:5000/v1/repositories/foreman/", host: "dcavm-ch2-053p.sys.comcast.net"

==> docker-registry.access.log <==
192.192.192.192 - rmoral00 [25/Mar/2014:15:42:22 +0000] "PUT /v1/repositories/foreman/ HTTP/1.1" 200 2 "-" "docker/0.8.1 go/go1.2 git-commit/a1598d1 kernel/3.13.5+ os/linux arch/amd64" "-"
192.192.192.192 - - [25/Mar/2014:15:42:22 +0000] "GET /v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json HTTP/1.1" 401 194 "-" "docker/0.8.1 go/go1.2 git-commit/a1598d1 kernel/3.13.5+ os/linux arch/amd64" "-"
192.192.192.192 - - [25/Mar/2014:15:42:22 +0000] "PUT /v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json HTTP/1.1" 401 194 "-" "docker/0.8.1 go/go1.2 git-commit/a1598d1 kernel/3.13.5+ os/linux arch/amd64" "-"
```

Any help resolving this would be appreciated, I have the suspicion that it may be related to the nginx configuratio but I need it there for authentication of users.

**Comment by ssalvatori** [comment]
sinchb: +1 what was the issue?

**Comment by sinchb** [comment]
@ssalvatori @rchaudha 
This is my nginx config. It works well:

```
FILE: registry.nginx

upstream docker-registry {
    server localhost:5001;
}

server {
    listen *:5000;
    server_name www.example.com;

    ssl on; 
    ssl_certificate  /etc/nginx/sites-cert/example.crt;
    ssl_certificate_key  /etc/nginx/sites-cert/example.key;

    client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

    # required to avoid HTTP 411: see Issue #1486 (https://github.com/dotcloud/docker/issues/1486)
    chunked_transfer_encoding on; 

    location / { 
        # let Nginx know about our auth file
        auth_basic              "Restricted";
        auth_basic_user_file    /etc/nginx/docker-registry.htpasswd;
        include /etc/nginx/docker-registry.conf;
    }   
    location /_ping {
        auth_basic off;
        include /etc/nginx/docker-registry.conf;
    }   
    location /v1/_ping {
        auth_basic off;
        include /etc/nginx/docker-registry.conf;
    }   
}
```

FILE: docker-registry.conf

```
proxy_pass                       http://docker-registry;
proxy_set_header  Host           $http_host;   # required for docker client's sake
proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP
proxy_set_header  Authorization  ""; # see https://github.com/dotcloud/docker-registry/issues/170
proxy_read_timeout               900;
```

**Comment by cdwertmann** [comment]
I've had this issue when using mirroring in the docker registry container. Mirroring and basic auth do not work together, so turning off mirroring fixed the issue for me. See
https://github.com/docker/docker-registry/issues/576#issuecomment-56017584

**Comment by mboersma** [comment]
This problem occurs constantly when uploading to Docker Hub itself.

`HTTP code 500 while uploading metadata: invalid character '<' looking for beginning of value`

We are using Docker v1.5.0 which should contain docker/docker#5083.

**Comment by ghost** [comment]
I am running into both the 500 invalid character < and 404 invalid character in my case a p character.  Debug Docker logs are useless.  This just started happening today.  I am noting my issue here but I am going to be opening a case with Docker's support team.  I attempted using both my Development and Integration Docker servers and they both are producing this error when I am pushing an image that I've just built.

**Comment by mboersma** [comment]
> I am running into both the 500 invalid character < and 404 invalid character in my case a p character

We are also getting that error:

```
773995669d83: Pushing
time="2015-07-07T14:36:19-06:00" level="fatal" msg="HTTP code 404 while uploading metadata: invalid character 'p' after top-level value" 
```

Something changed in Docker Hub's configuration on Sunday morning; that's when this all broke.

**Comment by shin-** [comment]
Please contact support for hub-related issues. I've notified people internally about the issue but having those tickets in the system versus on an old github report on a deprecated repo is infinitely more valuable and helps us track and update you about status much better.

**Comment by ghost** [comment]
Case # 5390 waiting for support to get back to me.

**Comment by shin-** [comment]
:+1:

**Comment by mboersma** [comment]
I have also filed support tickets for these issues.

**Comment by ghost** [comment]
Support would like me to upgrade to 1.6 for V2 registry.  They've asked me to turn on debug and supply them the logs.  Unfortunately the logs already provided by me were with debug switched on for the daemon.  Below is their response.  I've asked if there is anything else I can do without upgrading.

<SUPPORT>
It seems to me like you are using docker version 1.5. Looks like a problem with V1 registry right now. It looks like a server error to me, not an error on your side.

Can you try pushing with docker version 1.6 or above ( which uses V2 registry )?

If you cannot upgrade, can you please run your docker daemon in debug mode ( with -D -d ) and then reproduce the same error and send the daemon logs to us? We can check with the issue that way.
</SUPPORT>

**Comment by gopal-gemini** [comment]
its fixed for me after changed the following value in nginx conf.

error : 
HTTP code 413 while uploading metadata: "invalid character '<' looking for beginning of value"
fix:
client_max_body_size 0;
