### ISSUE TITLE
HTTP code 502 while uploading metadata: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by coderlol** [docker/docker-registry#320]
Using docker-registry, fronted by Apache, I get the 502 error from time to time.  Pushing again usually helps, but it's a pain as the sporadic 502 makes automation harder.

...
42ff9d5d213a: Image successfully pushed
0640d16acaa9: Image successfully pushed
5187f1faccd4: Pushing
2014/04/20 23:14:18 HTTP code 502 while uploading metadata: invalid character '<' looking for beginning of value

**Comment by drobison00** [comment]
Seeing this running a private docker registry running https authentication with an nginx proxy, and a swift backend. No errors if I push directly to the registry (port 5000).

docker login ....
Login Succeeded

511136ea3c5a: Pushing 
2015/02/05 12:47:14 HTTP code 502 while uploading metadata: invalid character '<' looking for beginning of value

docker version
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa/1.3.3
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa/1.3.3

**Comment by dmp42** [comment]
@drobison00 if it's working directly to the registry, then your issue is likely with your nginx configuration.

Without at least your nginx version number, your nginx configuration and nginx logs during the failure, it will be very hard to advise...

**Comment by mimizone** [comment]
In case it helps, I have the same issue with similar setup : nginx in front, authentication, https, swift backend.
it seems to be a timeout on the backend. I am still investigating.

**the error message on the docker client side**
```
ubuntu@docker-registry:~/nginx$ sudo docker push docker-registry.os/ubuntu
The push refers to a repository [docker-registry.os/ubuntu] (len: 1)
Sending image list
Pushing repository docker-registry.os/ubuntu (1 tags)
Image 511136ea3c5a already pushed, skipping
27d47432a69b: Pushing
FATA[0060] HTTP code 504 while uploading metadata: invalid character '<' looking for beginning of value
```

some info on my setup.

**nginx version** 1.6.2
deployed within a container from latest on docker.io

**registry**
in a container, based on the docker.io image, with the addition of the swift module and with config files embedded in the container

**/etc/nginx/nginx.conf**
```
root@617a0715e38d:/var/log/nginx# cat /etc/nginx/nginx.conf
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}

daemon off;
```

**/etc/nginx/sites-enabled/default**
```
upstream docker-registry {
 server registry:5000;
}

server {
 listen 443;
 server_name docker-registy;

 ssl on;
 ssl_certificate /etc/ssl/certs/docker-registry;
 ssl_certificate_key /etc/ssl/private/docker-registry;

 proxy_set_header Host       $http_host;   # required for Docker client sake
 proxy_set_header X-Real-IP  $remote_addr; # pass on real client IP

 client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

 # required to avoid HTTP 411: see Issue #1486 (https://github.com/dotcloud/docker/issues/1486)
 chunked_transfer_encoding on;

 location / {
     # let Nginx know about our auth file
     auth_basic              "Restricted";
     auth_basic_user_file    docker-registry.htpasswd;
     proxy_pass http://docker-registry;
 }
 location /_ping {
     auth_basic off;
     proxy_pass http://docker-registry;
 }
 location /v1/_ping {
     auth_basic off;
     proxy_pass http://docker-registry;
 }

}
```

**/var/log/nginx/access.log**
```
root@617a0715e38d:/var/log/nginx# cat access.log
172.30.8.33 - - [06/Feb/2015:00:22:54 +0000] "GET /v1/_ping HTTP/1.1" 200 2 "-" "Go 1.1 package http"
172.30.8.33 - - [06/Feb/2015:00:22:54 +0000] "GET /v1/_ping HTTP/1.1" 200 2 "-" "Go 1.1 package http"
172.30.8.33 - octopus [06/Feb/2015:00:22:55 +0000] "PUT /v1/repositories/ubuntu/ HTTP/1.1" 200 2 "-" "docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.13.0-40-generic os/linux arch/amd64"
172.30.8.33 - octopus [06/Feb/2015:00:22:55 +0000] "GET /v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json HTTP/1.1" 200 698 "-" "docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.13.0-40-generic os/linux arch/amd64"
172.30.8.33 - octopus [06/Feb/2015:00:22:55 +0000] "GET /v1/images/27d47432a69bca5f2700e4dff7de0388ed65f9d3fb1ec645e2bc24c223dc1cc3/json HTTP/1.1" 400 49 "-" "docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.13.0-40-generic os/linux arch/amd64"
172.30.8.33 - octopus [06/Feb/2015:00:23:55 +0000] "PUT /v1/images/27d47432a69bca5f2700e4dff7de0388ed65f9d3fb1ec645e2bc24c223dc1cc3/json HTTP/1.1" 504 182 "-" "docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.13.0-40-generic os/linux arch/amd64"
```

**/var/log/nginx/error.log**
```
cat error.log
2015/02/06 00:23:55 [error] 17#0: *11 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.30.8.33, server: docker-registy, request: "PUT /v1/images/27d47432a69bca5f2700e4dff7de0388ed65f9d3fb1ec645e2bc24c223dc1cc3/json HTTP/1.1", upstream: "http://172.17.0.3:5000/v1/images/27d47432a69bca5f2700e4dff7de0388ed65f9d3fb1ec645e2bc24c223dc1cc3/json", host: "docker-registry.os"
```

**Comment by mimizone** [comment]
I see some issues between the registry and the swift backend:

in docker registry logs:
```
06/Feb/2015:00:43:06 +0000 INFO: Starting new HTTP connection (1): 172.30.80.20
06/Feb/2015:00:43:16 +0000 INFO: REQ: curl -i http://172.30.80.20:8080/swift/v1/octopus_docker/registry/images/27d47432a69bca5f2700e4dff7de0388ed65f9d3fb1ec645e2bc24c223dc1cc3/json -X PUT -H "X-Auth-Token: 58e927ec80674f4ca23bc93e7e6440d5"
06/Feb/2015:00:43:16 +0000 INFO: RESP STATUS: 408 Request Time-out
06/Feb/2015:00:43:16 +0000 INFO: RESP HEADERS: [('connection', 'close'), ('content-type', 'text/html'), ('cache-control', 'no-cache')]
06/Feb/2015:00:43:16 +0000 INFO: RESP BODY: <html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
```

trying the curl request separately form the docker host:
```
curl -i http://172.30.80.20:8080/swift/v1/octopus_docker/registry/images/27d47432a69bca5f2700e4dff7de0388ed65f9d3fb1ec645e2bc24c223dc1cc3/json -X PUT -H "X-Auth-Token: 58e927ec80674f4ca23bc93e7e6440d5"
HTTP/1.1 411 Length Required
Date: Fri, 06 Feb 2015 00:44:22 GMT
Server: Apache/2.2.22 (Ubuntu)
etag:
Accept-Ranges: bytes
Content-Length: 20
Vary: Accept-Encoding
Connection: close
Content-Type: text/plain; charset=utf-8
```

**Comment by drobison00** [comment]
@dmp42 
Thanks, you're right. I was setting a header value in two places and it was causing a problem.

**Comment by drobison00** [comment]
@mimizone 
Thanks for this. My setup is almost identical; however, timeouts weren't was was getting me.  I'd set the 'Host' header to $host in one place, and $http_host in another. :(

**Comment by mimizone** [comment]
@drobison00 
thanks, I'll check on my side, but it doesn't seem to be the issue for me.
could you share your nginx config? and how you added the swift plugin and if you have specific config for this?

**Comment by drobison00** [comment]
For the swift plugin, I built up a new container from the basic registry.

=== Dockerfile ===
# Official registry image
FROM registry:latest

# Update config
ADD ./reg_config.yml /docker-registry/config/config.yml

# Update repository information
RUN apt-get -y update && apt-get -y upgrade

# Install build packages for docker swift driver
RUN apt-get -y install libxml2-dev && apt-get -y install libxslt-dev

# Install swift driver
RUN pip install docker-registry-driver-swift

=== End === 

The back end i'm using doesn't support swift's v2 authorization, so I added the following to my swift block in the .yml config used above:

swift_auth_version: _env:OS_AUTH_VERSION

Then at launch: -e OS_AUTH_VERSION=1

=== /etc/nginx/sites-enabled/docker-registry ===
upstream docker-registry {
    server localhost:5000;
}

server {
    listen 8080;
    server_name repo;

    ssl on;
    ssl_certificate /etc/ssl/certs/docker-registry-bundle.crt;
    ssl_certificate_key /etc/ssl/private/docker-registry.key;

    proxy_set_header Host       $http_host;   # required for Docker client sake
    proxy_set_header X-Real-IP  $remote_addr; # pass on real client IP

    client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

    # required to avoid HTTP 411: see Issue #1486 (https://github.com/dotcloud/docker/issues/1486)
    chunked_transfer_encoding on;

    location / {
        # let Nginx know about our auth file
        auth_basic              "Restricted";
        auth_basic_user_file    docker-registry.htpasswd;

        proxy_pass http://docker-registry;
    }

    location /_ping {
        auth_basic off;
        proxy_pass http://docker-registry;
    }

    location /v1/_ping {
        auth_basic off;
        proxy_pass http://docker-registry;
    }
}
==== end ====

**Comment by mimizone** [comment]
thanks for the info.
I built my containers basically the same way.
My swift supports v2 authentication. Switching to v1 as you did actually doesn't work at all for me unfortunately.

**Comment by mimizone** [comment]
For info, my issue was network related, with MTU discrepancy between nodes.
