### ISSUE TITLE
service should be able to start, even when backing store is unreachable or down

### ISSUE THREAD

**Issue by tamsky** [docker/docker-registry#354]
Our internal S3-compatible API service was recently changed to resemble being unavailable.
This caused docker-registry to stop (separate issue #tbd)

While trying to restart docker-registry, while the S3 service was still down, it was discovered that docker-registry is unable to start while the storage backend service is down.

  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 419, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)

docker-registry is issuing valid "HEAD /" requests, but our internal S3 service is temporarily (and incorrectly) returning 405 codes.

docker-registry workers, at startup, should be able to deal with this situation and initiate an exponentia- backoff/retry behavior.

**Comment by stevvooe** [comment]
Superseded by docker/distribution#54.
