### ISSUE TITLE
Branch and maintenance strategy

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#403]
We need a (preferably lightweight) way to issue bugfixes releases (say 0.7.1, 0.7.2).

Either we create a `0.7` branch from the tagged 0.7.0 (then later another `0.8` one, etc), or we create a `stable` branch of the tagged release, which is always exactly the last released version. IMO, avoiding the proliferation of branches is cool, but admittedly the history might be less obvious from a single `stable` branch.

@wking, @shin- @samalba and others, what do you think?

**Comment by wking** [comment]
On Mon, Jun 02, 2014 at 01:58:43AM -0700, wrote:

> We need a (preferably lightweight) way to issue bugfixes releases
> (say 0.7.1, 0.7.2).
> 
> Either we create a `0.7` branch from the tagged 0.7.0 (then later
> another `0.8` one, etc), or we create a `stable` branch of the
> tagged release, …

I prefer <major>.<minor> branches like 0.7.  That allows you to create
0.8 off master at the beginning of the feature freeze, while still
maintaining 0.7 for additional point releases until you cut 0.8 (or
until interest/funding for 0.7 support dries up ;).  That said, I
think you only need a formal procedure to maintain old releases once
you hit 1.0.  Early adopters shouldn't have problems upgrading to 0.8.
