### ISSUE TITLE
Struggling to setup a private repository

### ISSUE THREAD

**Issue by djl197** [docker/docker-registry#455]
All,

I have setup a private repository using local storage:
I have then started the service running.

On another machine I then build and tag a container:
docker tag <tag_num> docker-registry.DOMAIN/jenkins_slave

I then try and push to the registry:
sudo docker push docker-registry.DOMAIN/jenkins_slave
The push refers to a repository [docker-registry.DOMAIN/jenkins_slave](len: 1)
Sending image list

But thats it - I dont see anything else (like it actually pushing).
I have looked on the server and the logs show absolutely nothing - even with debug enabled.

I have obviously missed a really silly step out - but any help appreciated in debugging this?
Cheers
Dan

**Comment by mlnsharma** [comment]
@chewmanfoo How did you get around the mcafee firewall problem ? I am also observing "Error: Status 502 trying to push repository " issue. Can you please help.
