### ISSUE TITLE
Can't redirect stdout to log file

### ISSUE THREAD

**Issue by davemackintosh** [docker/docker-registry#469]
I've been trying (rather futilely) to try and stop docker-registry from writing to stdout but rather a log but I think the underlying Python is creating processes which seem to bypass all efforts of channelling to a log.

I've tried the usual `>` and `2>&1` and with piping to various commands but it all seems to escape my grasp. 

Is there anyway I can get **all** output of this command to go straight to a log rather than stdout?

This is the script I'm using to start it up, it's part of a shell script I plan to use as a service

```
start() {
  # Sugar
  echo -e "Starting registry"

  # Run the registry
  export LOGLEVEL=NOTSET
  export AWS_BUCKET=$TargetBucket
  export AWS_KEY=$AWSAccessKey
  export AWS_SECRET=$AWSSecretKey
  docker-registry & 2>&1 | tee $LogFile

  # Create a lock file
  touch $LockFile
}
```

I installed docker-registry via pip, I'm running CentOS 6.5 and Docker version 1.0.0

**Comment by Davidrjx** [comment]
@Furze in docker/distribution registry 2.6.2, is your first solution valid? did you rebuild registry image with gunicorn?
