### ISSUE TITLE
API /v1/repositories/(repo)/tags inconsistency from Docker Hub

### ISSUE THREAD

**Issue by tdooner** [docker/docker-registry#517]
There is an inconsistency between this project and the official Docker registry in the `/v1/repositories/:repo/tags` API endpoint. (I apologize if this isn't the right place to raise this, but since this project is pseudo-official, it seems reasonable that someone reading this can do something about it.)

Anyway, the details:

``` bash
» curl https://registry.hub.docker.com/v1/repositories/centos/tags
[{"layer": "b157b77b", "name": "latest"}, {"layer": "b1bd4990", "name": "centos6"}, {"layer": "b157b77b", "name": "centos7"}]

» curl -v [our-docker-registry]/v1/repositories/[repo]/tags
# [...snip...]
< HTTP/1.1 200 OK
# < [...snip...]
< X-Docker-Registry-Version: 0.7.3
< X-Docker-Registry-Config: dev

{"0.1": "e9c379f8772deab9b73c7a2dfd2a70bbd732cfda5d214c584d2f9982068282bc", "0.2": "124914b453965d5b5f6ad4d687ad6f93a98b787dca68defdec7ac9d05d2fdddf"}
```

This is kind of unfortunate, since clients must implement two different behaviors as to whether or not the official registry is being accessed. It appears that this project has the correct behavior (per the [API documentation](https://docs.docker.com/reference/api/registry_api/#tags)), so I suppose I'm really asking if the official registry has plans to release a new version of its API that is compatible?

Thanks!

**Comment by envygeeks** [comment]
And how do we go about obtaining a token because our builders are struggling to delete old tags and keep our account clean but I can't see anywhere on my settings page how to even get a token on both private and public registries.

**Comment by dmp42** [comment]
@envygeeks I guess you are talking about the hub?

Then your question should go to https://support.docker.com

**Comment by bacongobbler** [comment]
For public reference, you have to make a GET call to the image in question to retrieve the token.

```
><> curl -si https://registry.hub.docker.com/v1/repositories/library/ubuntu/images -H 'X-Docker-Token: true' | grep X-Docker-Token
X-Docker-Token: signature=01b8e3d3ef56515b33d9f68824134e3460de3a1a,repository="library/ubuntu",access=read
```

You can then use this token against the CDN for this image:

```
><> curl https://cdn-registry-1.docker.io/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json -H 'Authorization: Token signature=01b8e3d3ef56515b33d9f68824134e3460de3a1a,repository="library/ubuntu",access=read'
{"id":"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158","comment":"Imported from -","created":"2013-06-13T14:03:50.821769-07:00","container_config":{"Hostname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Dns":null,"Image":"","Volumes":null,"VolumesFrom":""},"docker_version":"0.4.0","architecture":"x86_64"}
```

Again, this is just for DockerHub, not for the open source registry. :)

**Comment by dmp42** [comment]
Thanks @bacongobbler 

I would just add that you need to add this: `--basic -u username:password` if you want access to your private stuff.

**Comment by envygeeks** [comment]
That's exactly what I needed so we could automate our tag removals, thanks @bacongobbler

**Comment by mconigliaro** [comment]
Before anyone else wastes half a day trying to figure out how to delete tags from Docker Hub using the API, here's what they told me:

"The documentation for deleting tags are only supposed to be used for private registries. DockerHub, on the other hand, does not allow these API calls to be made. Even, if you get the token, they have weird effects on images. We will very soon expose the APIs with V2 registry. For now, you can only use them to list the tags. DELETE and PUT are not being exposed yet."

I ended up having to scrape the web UI. :smile:
