### ISSUE TITLE
how to setup automated build with private docker registry?

### ISSUE THREAD

**Issue by vishnudxb** [docker/docker-registry#530]
I setup a private  docker registry and I can pull / push to my private registry. However right now I face some challenges in setting up automated build with github.  I create a webhooks in github but how  to connect it to the private docker registry ?

**Comment by stephaneeybert** [comment]
The web hook in github.com triggers the Jenkins build, which calls the build of which image ? Does your Jenkins build do a re build of all your images whatever the impacted branch in the hierarchy ?

**Comment by lrodri29** [comment]
@danielkraaij  Do you have open source instructions on how you do that? I am actually looking to do the exact same thing.
