### ISSUE TITLE
NG: extension model

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#613]
We need an "extension model" that will let people author useful optional features to the registry.

Registry v1 supported extensions as separate python packages that would consume signals.

Right now, the following ideas have been suggested:

 * use https://github.com/docker/libchan
 * use https://github.com/docker/libswarm
 * use plain old-school http and long polling
 * use mitchell plugins: https://github.com/mitchellh/packer/tree/master/packer/plugin
 * hard compile the extensions in
 * expect go to support dynamic loading

Now, figuring out the proper "communication channel" is only half of the story, and we should also design the API itself.

Your input welcome!

**Comment by stevvooe** [comment]
Superseded by docker/distribution#136.
