### ISSUE TITLE
NG: irc hands-on meetings

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#622]
I would like to have some regular irc sessions to address ongoing questions that are not that easy to address on tickets, or kickstart architectural decisions by quickly sketching out things.

Now, just popping randomly on docker-dev and chatting there doesn't fly well, so, I would rather have something a bit more planned so that every one interested can free-up their schedule ahead of time.

These don't have to be long - just a way to stay synched with everyone and have things move ahead.

So:

 * what about 10AMPST on mondays
 * what about next monday topic: reach consensus on the auth architecture

**Comment by stevvooe** [comment]
We've already started doing this at 10AM PST on Mondays.
