### ISSUE TITLE
NG: Transactional storage

### ISSUE THREAD

**Issue by wking** [docker/docker-registry#626]
We've had some difficulties ensuring atomic transactions with the current registry.  This makes it difficult to do things like [robustly refcount images][1] (or anything else where you'd need to touch metadata in several locations at once).  I've been poking around to get a feel for how other folks handle transactions with huge.

* Redis (and most key/value stores we might use for the smaller metadata) [supports transactions][2], and there is support [in asyncio-redis][3], if we end up implementing the new registry in Python with [aiohttp][4].
* Transactional filesystems seem a bit harder to come by, but if you don't have a huge volume of them, you can likely squeak by with something like Toggenburger's [libbtrfstrans][5] (although the paper doesn't seem to be maintained or have version-controlled code).
* Microsoft's SQL Server supports [FILESTREAM][6], which seems to give transactional access through the database layer, but stores the actual blobs transparently to the filesystem.  Oracle Database has something similar with [BFILE][7].
* Gropengießer and Sattler have a [paper on transactional S3][8].  I only skimmed it, but it seems to be talking about a unpublished code for their client library and service layer.

This is not my area of expertise though, and its certainly possible that there's a mainstream, open-source, transactional storage solution for large binary blobs; I just can't find it ;).

[1]: https://github.com/docker/docker-registry/pull/409#issuecomment-45125628
[2]: http://redis.io/topics/transactions
[3]: https://github.com/jonathanslenders/asyncio-redis#transactions-example
[4]: https://github.com/KeepSafe/aiohttp
[5]: http://wiki.hsr.ch/Datenbanken/files/report.pdf
[6]: http://msdn.microsoft.com/en-us/library/gg471497.aspx#storage
[7]: http://docs.oracle.com/cd/B10501_01/appdev.920/a96591/adl12bfl.htm
[8]: http://www.dbis.prakinf.tu-ilmenau.de/publications/files/DBIS:GroSat11.pdf

**Comment by stevvooe** [comment]
We are using this discussion in the ongoing roadmap for distribution but don't have actionable work based on this issue. Closing for now.
