### ISSUE TITLE
NG: api-doc-driven model

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#627]
Admittedly, the documentation for v1 (https://docs.docker.com/reference/api/registry_api/) was not so great and we had problems keeping it up to date.

Some experiments is going on to use swagger for other parts of the project (https://github.com/docker/docker/pull/8402) so I would like to evaluate if that would fly for us and/or how to fix our previous shortcomings.

**Comment by stevvooe** [comment]
We are following this model for the next-generation registry with the [descriptors](https://github.com/docker/distribution/blob/master/api/v2/descriptors.go). These can be used to generate documentation with templates or definitions for implementing clients in other languages. They could also be used to directly generate swagger documentation.

Closing as completed for now. We may have specific tasks that are related to this in the docker/distribution repository.
