### ISSUE TITLE
NG: Logging

### ISSUE THREAD

**Issue by dmcgowan** [docker/docker-registry#635]
Define a standard way to log across in the registry in a uniform and easy to process manner.  Some topics to decide on...

- Log format (logfmt, json, google-glog, something else)
- Log output (stderr, file)
- Error handling (stack traces and error wrapping)
- Log context (how to group log lines to specific requests)

The main concern is balancing a uniform method and format with something that is flexible.  Flexibility meaning customization can be done on top of what is decided, and questions about whether to use volumes, which agent forwarder, or pipe logs through log rotation script X don't need to be discussed here.

**Comment by stevvooe** [comment]
Superseded by docker/distribution#86.
