### ISSUE TITLE
"Tag latest not found in repository" when pulling

### ISSUE THREAD

**Issue by joshk0** [docker/docker-registry#637]
In docker 1.2.0, this worked:

   docker pull my-registry:443/centos

In docker 1.3.0, it returns the following error:

  2014/10/17 16:08:42 Tag latest not found in repository my-registry:443/centos

Here's the layout in the repository (it is true, there is no latest tag):

   kwan@docker-registry:/vol/docker/registry/images/repositories/library/centos$ ls
   _index_images  tag_6.4  tag6.4_json

Is this a change in defined functionality somewhere (either with the registry or with something else?) Even if it is, I would expect some kind of compatibility behavior for repos without this 'latest' tag.

**Comment by mesco64** [comment]
Thanks this solved my problem. This error was happening when attempting to pull the cmdbuild container
terminalvelocity/cmdbuild
