### ISSUE TITLE
NG: healthcheck endpoints

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#656]
User stories

 * I'm a devops, and I want a simple way to check whether all dependent systems are operational from a registry perspective
 * I'm a devops, and I want pingdom to query a specific endpoint and have it fail if the registry is not actually functioning, for any reason

This shouldn't disclose/leak any sensitive information, but still give enough info about what's happening.

Also, checking backend services health (redis, storage) might be long and shouldn't let the endpoint timeout, so, these checks should be done asynchronously and they should timeout before the endpoint does.

Maybe this could be designed as an extension?

@ncdc @noxiouz @BrianBland go crazy :-) - there was a discussion started about that already at #482

**Comment by stevvooe** [comment]
Superseded by docker/distribution#133.
