### ISSUE TITLE
NG: mirroring model

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#658]
The current registry supports mirroring.
We need to have the same kind of feature.

The bottom-line is:

 * act as a caching proxy, likely with configurable TTL on manifest files
 * support bytes-range end-to-end

**Comment by bobrik** [comment]
As mentioned in docker/docker#9161, there should be a way to enable/disable mirroring for registries. You probably don't want to mirror your own registry that is accessible over 10G network, but want to do so with docker hub and registries hosted by other people.

**Comment by bobrik** [comment]
Another thing I'd love to see explained is how mirroring with one storage (like s3) and many registries (like 5 processes on different nodes for HA and scalability) works.

**Comment by stevvooe** [comment]
This issue has been superseded by docker/distribution#19, which includes an overview of the intended implementation.

@bobrik Actual storage for mirroring will be accomplished within the registry. If the registry is not configured as a mirror, content will not be pulled from that registry. We may be able to make caching the content locally an optional configuration parameter to allow for local, non-cached mirrors. The client can be pointed at the local registry, deferring the decision of whether to fetch the remote content to the local registry. The new registry will be able to run as a cluster with a shared storage backend, allowing for HA and scaling. For the most part, nodes are shared-nothing except for the storage backend and possibly a caching system, such as redis.

**Comment by stevvooe** [comment]
Superseded by docker/distribution#19.
