### ISSUE TITLE
NG: extension: basic search functionality

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#687]
We need to provide basic search as part of the standard registry API.

A couple of words:

 * this must be usable by docker engine as it is today
 * in the best of worlds, that would be an extension, that would get notified on PUT manifest and that would expose an additional endpoint (see v1 API)
 * we want to leave room for concurrent search implementations (batteries included, removable)
 * re-indexing from scratch should not be part of the extension itself (eg: at start / runtime) but rather handled by a separate script accessing the backend storage
 * the extension should not need access to the storage at runtime

**Comment by stevvooe** [comment]
This should be covered by docker/distribution#113. An microservice accepting notification requests could index repositories.

If not, please re-open.
