### ISSUE TITLE
NG: quotas

### ISSUE THREAD

**Issue by ncdc** [docker/docker-registry#698]
We would like to be able to proactively reject an attempt to upload any/all layers for a new image/tag if the sum of the size of all the new layers would result in a quota violation.

Example: my namespace is currently at 700MB and I'm pushing a new image/tag that has 400MB of unique layer content split between 2 layers (299MB and 101MB). First my client would push the 299MB layer (which keeps me under quota), then my client would attempt to push the 101MB layer (which should not be allowed because that would put me over quota). At this point, there's an orphaned 299MB layer that should be deleted. In an ideal case, the registry should never have allowed that layer to have been uploaded in the first place.

Possible quota scopes:
- namespace (all repositories in a namespace share a pool of quota)
- repository (an individual repository has its own quota)

In order for the registry to make the quota determination up front, the client will likely need to begin by telling the registry the layers in the image and the size of each layer. The registry can make the determination as to which layers already exist vs which are new and then check if the upload of all the new layers would go over quota.

**Comment by samprog1** [comment]
Are there any news regarding quotas? Was there something like that implemented in v2?

**Comment by ncdc** [comment]
Closing as this repo is deprecated
