### ISSUE TITLE
NG: deprecation path and client messaging

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#734]
We might want in the future to "blacklist" some specific docker versions, or more simply to refuse push from too-old / unsupported anymore clients.

See #570 for why I want a provision for these cases *beforehand*.

That means we have a documented way on the registry that clients can honor to back-of.

Although UA sniffing is considered bad practice in the wider-web, it may be the simplest path - but maybe there are other ways to "identify" a problematic client.

As for the response, 412 + informative message?

**Comment by stevvooe** [comment]
There are a number of approaches we are taking with the new registry that will make this easier:

1. All docker clients do have a user agent with docker version. This won't change.
2. Future api implementations will require strict media type declarations in Accept headers for requests, making "turning off" old clients much easier.

Please open a specific issue in docker/distribution if the intent of this ticket isn't covered.
