### ISSUE TITLE
NG: registry debug tools

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#757]
We probably want to ship a set of helpers that would make reporting bugs and/or diagnosing easier.

On top of the head:

 * something to run network sanity tests and output a compact summary (dns resolution, ping latency, speed test measurement, sthing else?)
 * something to introspect and extract meaningful informations from the process / other helpers to maybe restart a registry in debug mode?
 * backend driver sanity report
 * dependency versions, extensions/backend driver version, system versions, os, kernel (?)
 * running configuration dump (possibly magically redacting secrets?)
 * standalone client tools to perform API tests requests to the registry
 * tools to extract registry related informations from the docker engine?
 * else?

I'm flagging as extension for now, though that doesn't have to be a "true" extension in itself (like "true APIs" :)).

cc @BrianBland @samalba

**Comment by stevvooe** [comment]
Superseded by docker/distribution#/198.
