### ISSUE TITLE
Using nginx proxy private docker registry

### ISSUE THREAD

**Issue by hordemark** [docker/docker-registry#812]
according to https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04

This post working on Ubuntu.  it could work well.
But testing on centos 6.5, when execute: curl USERNAME:PASSWORD@localhost:8080

Got error message:

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

anyone can help me

**Comment by leslau** [comment]
@hordemark Hi i'm having the same problem! Did u got a workaround for the problem!?

**Comment by shawinder** [comment]
Update:

I got a fix. It's because nginx proxy by defaul listens to port 80. You must specify registry port `500` in the proxy_pass url. Let me know if that helps.

Hi Guys,

Did you figure out what the problem was? I am also getting 502 with nginx proxy and docker registry setup.
