### ISSUE TITLE
NG: v2 must require properly formed UA string

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#817]
The UA string must contain `productname/semver`.

**Comment by stevvooe** [comment]
The goal of this ticket is satisfied for v2 registry with `User-Agent` header from docker daemon:

```
docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.16.7-tinycore64 os/linux arch/amd64
````

We can easily ban with buggy clients with by detecting docker version or git hash. We also have `Docker-Distribution-API-Version` to communicate from server to client.

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 03:58:42PM -0800, Stephen Day wrote:
> The goal of this ticket is satisfied for v2 registry with `User-Agent` header from docker daemon:
> 
> ```
> docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.16.7-tinycore64 os/linux arch/amd64
> ````

The problem wasn't the Docker daemon, it was the registry choking when
*other* clients were connecting (see #375).

> We can easily ban with buggy clients with by detecting docker
> version or git hash. We also have `Docker-Distribution-API-Version`
> to communicate from server to client.

We had been using User-Agent strings to work around buggy clients, and
server→client communication isn't going to fix a buggy client.

As I've said before [1], I'm fine with registry-side workarounds tied
to whatever you like, so long as they're optional.

[1]: https://github.com/docker/docker-registry/issues/817#issuecomment-65731487

**Comment by stevvooe** [comment]
@wking Using a User-Agent to deal with a buggy client is usually a bad idea. It does nothing but increase complexity and create future problems. However, we currently have the hooks to do this if it comes to that.

I'm not going to port this issue into the docker/distribution tracker unless it has a clear, actionable design. Right now, its open-ended and I'm not sure what a resolution would look like.

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 06:30:33PM -0800, Stephen Day wrote:
> @wking Using a User-Agent to deal with a buggy client is usually a
> bad idea.

I absolutely agree.

> However, we currently have the hooks to do this if it comes to that.

So long as the hooks don't break the registry if the User-Agent isn't
properly formed, I'm happy.
