### ISSUE TITLE
NG: Allow for subpath

### ISSUE THREAD

**Issue by dmp42** [docker/docker-registry#818]
The registry should not assume it's running at the root of the server.

eg: both https://myregistry/v2/ and https://myregistry/something/v2/ should be possible.

The typical scenario when this is happening is a registry being run through a corporate portal that would "mount" the registry backend on a subpath.

This remark is valid as well for client code to be written.  

See #284 for historical reference.

**Comment by stevvooe** [comment]
Superseded by docker/distribution#29.
