### ISSUE TITLE
Can't login (latest docker-registry image, nginx)

### ISSUE THREAD

**Issue by uhop** [docker/docker-registry#869]
## Problem

(Note: everywhere instead of `xxx.xxx.xxx` I use a real valid name).

That's what I am getting on a remote computer:

```
$ sudo docker login https://xxx.xxx.xxx/
Username: xxx
Password: 
Email: 
2014/12/19 15:04:55 Error response from daemon: (Code: 404; Headers: map[Server:[nginx/1.6.2 (Ubuntu)] Date:[Fri, 19 Dec 2014 21:04:57 GMT] Content-Type:[text/html] Connection:[keep-alive]])
```

That's how I start the image and its output that corresponds to the above attempt:

```
$ docker run -p 127.0.0.1:5000:5000 registry
2014-12-19 21:04:16 [1] [INFO] Starting gunicorn 19.1.0
2014-12-19 21:04:16 [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2014-12-19 21:04:16 [1] [INFO] Using worker: gevent
2014-12-19 21:04:16 [16] [INFO] Booting worker with pid: 16
2014-12-19 21:04:16 [19] [INFO] Booting worker with pid: 19
2014-12-19 21:04:16 [20] [INFO] Booting worker with pid: 20
2014-12-19 21:04:16 [21] [INFO] Booting worker with pid: 21
2014-12-19 21:04:16 [1] [INFO] 4 workers
19/Dec/2014:21:04:16 +0000 WARNING: Cache storage disabled!
19/Dec/2014:21:04:16 +0000 WARNING: LRU cache disabled!
19/Dec/2014:21:04:16 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
19/Dec/2014:21:04:16 +0000 WARNING: Cache storage disabled!
19/Dec/2014:21:04:16 +0000 WARNING: LRU cache disabled!
19/Dec/2014:21:04:16 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
19/Dec/2014:21:04:16 +0000 WARNING: Cache storage disabled!
19/Dec/2014:21:04:16 +0000 WARNING: LRU cache disabled!
19/Dec/2014:21:04:16 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
19/Dec/2014:21:04:16 +0000 WARNING: Cache storage disabled!
19/Dec/2014:21:04:16 +0000 WARNING: LRU cache disabled!
19/Dec/2014:21:04:17 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
172.17.42.1 - - [19/Dec/2014:21:04:57 +0000] "GET /_ping HTTP/1.0" 200 1435 "-" "Go 1.1 package http"
172.17.42.1 - - [19/Dec/2014:21:04:57 +0000] "GET /users/ HTTP/1.0" 404 233 "-" "docker/1.2.0 go/go1.2.1 git-commit/fa7b24f kernel/3.13.0-22-generic os/linux arch/amd64"
```

I tried without `127.0.0.1` part with the same result. I do know about STANDALONE &mdash; it is on by default, but I tried to specify it explicitly with zero positive results.

## nginx

This is the nginx config:

```nginx
upstream docker-registry {
  server localhost:5000;
}

server {
  listen 443;
  server_name xxx.xxx.xxx;

  ssl on;
  ssl_certificate /etc/ssl/certs/docker-registry;
  ssl_certificate_key /etc/ssl/private/docker-registry;

  client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
  chunked_transfer_encoding on;

  location / {
    auth_basic            "Restricted";
    auth_basic_user_file  /etc/nginx/docker-registry.htpasswd;
    include               /etc/nginx/docker-registry.conf;
  }

  location /_ping {
    auth_basic off;
    include               /etc/nginx/docker-registry.conf;
  }

  location /v1/_ping {
    auth_basic off;
    include               /etc/nginx/docker-registry.conf;
  }
}
```

The config is copied almost verbatim from `contrib/`. `docker-registry.conf` is copied from the same place without any modifications. I can see that the nginx part works when I specify wrong user/pass combinations, yet if it is correct I am getting the error above.

## Local

When I try to connect locally it works, kinda:

```
$ docker login localhost:5000
Username: xxx
Password: 
Email: 
Account created. Please see the documentation of the registry http://localhost:5000/v1/ for instructions how to activate it.
$ docker logout localhost:5000
Remove login credentials for localhost:5000
```

The URL in question `http://localhost:5000/v1/` is not there, and produces 404. Totally misleading, but at least it is something.

Given the above it looks like there is some kind of problem with proxying. Did I make any obvious mistakes? How can I troubleshoot it?

## Bonus

It is worth mentioning a minor bug as well that `docker-registry` uses redirects, which break proxying. For example, when I go to `https://xxx.xxx.xxx/v1/users` it redirects to `http://xxx.xxx.xxx/v1/users/` &mdash; notice `http` instead of `https` &mdash; and nginx responds with 404 as it should,

**Comment by uhop** [comment]
@benhosmer My registry is definitely running, because I can connect to it locally, as I indicated in my original post. I cannot access any URLs through a proxy, and, most importantly, docker doesn't think it is logged in.

**Comment by uhop** [comment]
@larrycai I can see that your config passes an extra header `X-Forwarded-Proto`, which is missing in the config suggested by `docker-registry/contrib`. It can easily be the real reason for the effect I am observing. Let me try it out, and I'll report results here.

**Comment by benhosmer** [comment]
@uhop: Suspecting you might be on to something with the `X-Forwarded-Proto`. I checked my nignx config:

    upstream docker-registry {                                                     
     server localhost:5000;                                                        
    }                                                                              
                                                                                   
    server {                                                                       
      listen 443 default_server;                                                   
      ssl on;                                                                      
      ssl_certificate  /etc/nginx/ssl/CA-BUNDLE-.cert.pem;                         
      ssl_certificate_key /etc/nginx/ssl/server.key.pem;                           
      proxy_set_header Host       $http_host;   # required for Docker client sake
      proxy_set_header X-Real-IP  $remote_addr; # pass on real client IP           
                                                                                   
      client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads
      chunked_transfer_encoding on; # required to avoid HTTP 411: see Issue #1486 (https://github.com/dotcloud/docker/issues/1486)
                                                                                   
      location / {                                                                 
        auth_basic "Restricted Location";                                          
        auth_basic_user_file /etc/nginx/htpasswd/.htpasswd;                        
        proxy_pass http://docker-registry;                                         
        #proxy_set_header    Host             $host;                               
        #proxy_set_header    X-Real-IP        $remote_addr;                        
        #proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;          
        #proxy_set_header    X-Client-Verify  SUCCESS;                             
        #proxy_set_header    X-Client-DN      $ssl_client_s_dn;                    
        #proxy_set_header    X-SSL-Subject    $ssl_client_s_dn;                    
        #proxy_set_header    X-SSL-Issuer     $ssl_client_i_dn;                    
        proxy_read_timeout 1800;                                                   
        proxy_connect_timeout 1800;                                                
      }                                                                            
      location /_ping {                                                            
        auth_basic off;                                                            
        proxy_pass http://docker-registry;                                         
      }                                                                            
      location /v1/_ping {                                                         
        auth_basic off;                                                            
        proxy_pass http://docker-registry;                                         
      }                                                                            
    }

This is my working config. I've got them commented out at this point.

**Comment by uhop** [comment]
It turned out that adding more headers do not help &mdash; I expected as much seeing that @benhosmer config doesn't list anything special. But I found the problem.

This is how I tried to connect:

```
sudo docker login https://xxx.xxx.xxx/
```

It fails with a cryptic message.

That's how it works:

```
sudo docker login xxx.xxx.xxx
```

From docs I understood that a server option should be in URL format:

```
$ docker help login

Usage: docker login [OPTIONS] [SERVER]

Register or log in to a Docker registry server, if no server is specified "https://index.docker.io/v1/" is the default.

  -e, --email=""       Email
  -p, --password=""    Password
  -u, --username=""    Username
```

Notice the full-blown URL https://index.docker.io/v1/ as the default.

The same is mentioned in [docs on login](https://docs.docker.com/reference/commandline/cli/#login).

Finally I decided to run @larrycai example (he helpfully lists a sequence of test commands, and even provides mock accounts and security certificates with the image), and noticed that his example uses a straight DNS name without any `http` / `https` part. It dawned on me to try it, and it worked.

Ideally this ticket should be converted to a documentation ticket, but I don't know where to correct the CLI help, and the web site. If it is specific only to a stand-alone version of docker-registry, it should be mentioned in readme, or an FAQ, if there is one.

I am closing the ticket for now. Thank you @larrycai and @benhosmer for helping me to troubleshoot the problem!

**Comment by StrongPa55word** [comment]
Getting same error with Nginx and Apache. Tried all things still not working

FATA[0006] Error response from daemon: (Code: 404; Headers: map[Content-Type:[text/plain; charset=utf-8] Date:[Wed, 17 Jun 2015 17:30:59 GMT] Docker-Distribution-Api-Version:[registry/2.0] Content-Length:[19] Connection:[keep-alive]])

**Comment by dmp42** [comment]
@titotp your problem is with the new registry - not the python one.
Furthermore, there is simply not enough information to diagnose this.
I answered you about that on the other ticket you opened.
