### ISSUE TITLE
How to pull images automatically from privilege warehouse ？

### ISSUE THREAD

**Issue by jothep** [docker/docker-registry#885]
When docker run a container which had no images on localhost,it will try to pull the images from public images warehouse.Can I let docker pull the images from my privilege warehouse by docker-registry?

**Comment by dmp42** [comment]
Either the image is stored on your private registry (eg: its name is `myprivateregistry/foo/bar`), and it will be fetched from there.
Either the image is stored on the central registry (eg: `foo/bar`) - in which case it will be pulled from there.

Can you elaborate a bit on what you are trying to achieve?

**Comment by jothep** [comment]
Can I set my docker-registry for default and I'll pull images from my private store?
For example:
I use 'docker run Ubuntu /bin/bash'
If localhost had no this image,It show 'Unable to find image 'Ubuntu' locally' and docker pull 'Ubuntu' image from my private store.

**Comment by jothep** [comment]
@dmp42

**Comment by dmp42** [comment]
The closest you can get to that would be to use mirrors.

 * configure your private registry as a mirror
 * `docker pull ubuntu --registry-mirror=https://myregistry`

**Comment by jothep** [comment]
thanks @dmp42
