### ISSUE TITLE
Repository deletion does not remove images

### ISSUE THREAD

**Issue by hvolpers** [docker/docker-registry#887]
Hi,

after deleting the only repository (curl -XDELETE registry:5000/v1/repositories/library/test_image) the images still exist. I there a way to delete the corresponding image(s) as well (as long as they are not used by another repo)? I'm using S3 as backend.

**Comment by dmp42** [comment]
Delete doesn't delete the layers themselves. You can search the "delete" label for more information and other reports about this.
