### ISSUE TITLE
docker client doesn't send HTTP authentication for /v1/search requests

### ISSUE THREAD

**Issue by omribahumi** [docker/docker-registry#891]
I'm using https://github.com/docker/docker-registry/blob/master/contrib/nginx/nginx_1-3-9.conf
`docker search` results `FATA[0002] Error response from daemon: Unexepected status code 401`

Disabling authentication for /v1/search (like /_ping) works around this.

**Comment by dmp42** [comment]
Hi. Can you PR the change so that others can use your fix?
That would be awesome.
