### ISSUE TITLE
Make it clear the 'next generation' isn't even functional yet

### ISSUE THREAD

**Issue by aidanhs** [docker/docker-registry#894]
```
Notice: This repository hosts the classic (stable) python docker-registry. If you are looking for the next-generation of docker distribution tools (including the new golang registry), please head over to docker/distribution instead.
```

I then spent 15 mins on docker/distribution trying to figure out the compatibility with versions of docker, how to set it up and so on. It was only when I happened to click a small link in the readme and read the entire ticket of docker/docker#9784 did I realise that not only is the registry not ready, the client doesn't even support it!

So it'd be nice to have a notice saying "Be aware that this is not currently ready for use, it's just where development effort will be shifting to." (possibly with an equivalent notice on the docker/distribution readme).

**Comment by dmp42** [comment]
Hi, thanks for the feedback on this.
Indeed, next-gen is under heavy development right now. 

I modified the readme slightly to make things clearer.
Let me know if you think this helps.

Best.

**Comment by aidanhs** [comment]
Looks good to me, thanks.
