### ISSUE TITLE
Does _ping return just "true"?

### ISSUE THREAD

**Issue by stozk** [docker/docker-registry#899]
Edit: Sorry I figured out that my auth settings were messed up. It works now, but the error messages confused me... please close this thanks.

Hi,

I'm struggling with pushing an image to my private registry. 
I've had it working when I used the dockerized registry, but I've installed a standalone instance yesterday, with nginx authorization etc..

So this appears in the docker log:
Invalid registry endpoint https://10.15.5.143:5000/v1/: Get https://10.15.5.143:5000/v1/_ping: tls: oversized record received with length 28012.

http://10.15.5.143:5000/v1/_ping returns:

{"host": ["Linux", "linux-vm-m-0001", "3.13.0-24-generic", "#47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014", "x86_64", "x86_64"], "launch": ["/usr/local/bin/gunicorn", "--access-logfile", "/var/log/docker-registry/access.log", "--error-logfile", "/var/log/docker-registry/server.log", "-k", "gevent", "--max-requests", "100", "--graceful-timeout", "3600", "-t", "3600", "-b", "localhost:5001", "-w", "8", "docker_registry.wsgi:application"], "versions": {"M2Crypto.m2xmlrpclib": "0.22", "SocketServer": "0.4", "argparse": "1.1", "backports.lzma": "0.0.3", "blinker": "1.3", "cPickle": "1.71", "cgi": "2.6", "ctypes": "1.1.0", "decimal": "1.70", "distutils": "2.7.6", "docker_registry.app": "0.9.1", "docker_registry.core": "2.0.3", "docker_registry.server": "0.9.1", "email": "4.0.3", "flask": "0.10.1", "gevent": "1.0.1", "greenlet": "0.4.5", "gunicorn": "19.1.1", "gunicorn.arbiter": "19.1.1", "gunicorn.config": "19.1.1", "gunicorn.six": "1.2.0", "jinja2": "2.7.3", "json": "2.0.9", "logging": "0.5.1.2", "parser": "0.5", "pickle": "$Revision: 72223 $", "platform": "1.0.7", "pyexpat": "2.7.6", "python": "2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]", "re": "2.2.1", "redis": "2.10.3", "requests": "2.3.0", "requests.packages.chardet": "2.2.1", "requests.packages.urllib3": "dev", "requests.packages.urllib3.packages.six": "1.2.0", "requests.utils": "2.3.0", "simplejson": "3.6.2", "sqlalchemy": "0.9.4", "tarfile": "$Revision: 85213 $", "urllib": "1.17", "urllib2": "2.7", "werkzeug": "0.9.6", "xml.parsers.expat": "$Revision: 17640 $", "xmlrpclib": "1.0.1", "yaml": "3.11", "zlib": "1.0"}}

Shouldn't it just return "true"?

I've checked the config.yml, debug information is not enabled:

 # Enable debugging (additional informations in the output of the _ping endpoint)
    debug: _env:DEBUG:false

Or doesn't this even matter at all?

BR
Daniel

**Comment by dmp42** [comment]
Closing - for the record, what you see there indicates debug is *true* indeed.
