### ISSUE TITLE
Issue with basic authentication on a private docker registry

### ISSUE THREAD

**Issue by paturuv** [docker/docker-registry#902]
The basic authentication on docker private registry using nginx is real tricky one. 
Not sure if that really works with docker client.

I have docker registry running on a ssl enabled server. I am using nginx to enable ssl and configured the basic authentication too.

The curl works find to connect to registry and get response. 
Where as the docker client can't go through with the following error message :
            Error response from daemon: Server Error: Post https://example.domain.com/v1/users/: 
            x509: certificate signed by unknown authority 

I have figured out that the docker won't work with self signed certificates and hence created a CA certificate and used the same, still the same issue.

Am I missing anything here or is it a bug?

I am using the same nginx configurations mentioned under /contrib/nginx under docker/docker-registry on git

**Comment by paturuv** [comment]
I could resolve this issue of login by following the below steps:
1. Place the certificate file (ca-bundle.crt) under /etc/pki/tls/certs
2. Running  update-ca-trust command
3. Restart the the docker service

**Comment by paturuv** [comment]
Though the login is successful, my pull requests are failing.
I looked in to the nginx log file then I could see a permission denied response

43543#0: *17 open() "/var/www/example.domain/.htpasswd" failed (13: Permission denied), client: <<IP address>>, server: example.domain.com:5000, request: "GET /v1/repositories/base/apache-2.2-base/images HTTP/1.1", host: "host name"

**Comment by dmp42** [comment]
Your nginx server does not have permission to access your .htpasswd file.
I assume nginx is running as `www-data`, so make sure that unix account has at least read access to your .htpasswd file.

**Comment by paturuv** [comment]
Hi -

I have added the user as owner of the file, still permission denied error.

Am I missing any thing here?

Thanks,
Venkat

**Comment by dmp42** [comment]
What user is used by nginx? (`ps aux | grep nginx` should give you a hint)
Then `su  THATUSER` and try to `cat /var/www/example.domain/.htpasswd` to validate your perm are ok.

**Comment by paturuv** [comment]
I have changed the .htpasswd permissions to 777

The nginx service is run by root

Thanks
Venkat

**Comment by dmp42** [comment]
Can you run: `ls /var/www/example.domain/.htpasswd` 

Thanks.

**Comment by paturuv** [comment]
I have changed the owner to root, still the same error
Following is the result of
ls -l
-rwxrwxrwx 1 root root 23 feb 16 21:00 /var/www/example.domain/.htpasswd

Thanks
Venkat

**Comment by dmp42** [comment]
Are all directories along that path executable for the nginx user?
eg: `/var` `/var/www` `/var/www/example.domain`

Either way, this really is a nginx configuration problem, not a registry issue.

**Comment by paturuv** [comment]
I shall check the permissions recursively. Thank you.

I have another issue related to docker registry api, set a tag for specific image is is not working, not sure if I can work with you to resolve the same

Thanks,
Venkat

**Comment by dmp42** [comment]
The bugtracker here is rather meant for feature requests and bug report, not support.
I'm happy to help as time permits, but you should rather direct support questions to irc / forums.

**Comment by paturuv** [comment]
Thank you so much. I really appreciate your support

Thanks,
Venkat
