### ISSUE TITLE
Automated build repo creation fails from Bitbucket

### ISSUE THREAD

**Issue by teodorescuserban** [docker/docker-registry#913]
I have a bunch of automated build images on Docker Hub.
The images are based on private repos on Bitbucket.
Everything is peachy.

However, I tried to add a new automated build from another Bitbucket private repo and I get ```500 Internal Server Error``` after I submit the repo details.

Afterwards, the docker registry repo is created, but clicking on "Build" tab throws ```404 Not Found```.
I cannot see the ```Deployment Keys``` link.

On the BitBucket side, there are no deployment keys added, however, there it the ```POST``` hook added.

This error appears to have popped up very recently, as my last created repo is created less than 10 days ago.

Thank you for your help.

**Comment by dmp42** [comment]
Hi @teodorescuserban this here is the open-source registry.
To report bugs on the hub (specially automated builds), you should report to https://support.docker.com instead.

**Comment by teodorescuserban** [comment]
thank you, @dmcgowan
