### ISSUE TITLE
Missing documentation on HA and scaling in README or FAQ

### ISSUE THREAD

**Issue by mattford63** [docker/docker-registry#923]
Hi,

There is no information on the above.  In particular

- is it safe to use a common storage backend (say S3) across multiple registry containers
- is it safe/should one use a common Redis  server across multiple registry containers
- is it safe/should one use a commom SQLAlchemy end-point across multiple containers

Matt.

**Comment by dmp42** [comment]
Yes to all questions :)

**Comment by dmp42** [comment]
Indeed, an additional "scaling" paragraph may definitely be added to https://github.com/docker/docker-registry/blob/master/ADVANCED.md

**Comment by Aayush-Kasurde** [comment]
I think this issue is addressed with PR #927 
@dmp42 Could you please mark this issue as closed ?
