### ISSUE TITLE
run docker registry -p seems to fail

### ISSUE THREAD

**Issue by wenlock** [docker/docker-registry#930]
Hi, I'm trying this command on a new ubuntu box.

```docker run -p 5000:5000 registry```

When i remove the `-p 5000:5000` option, everything starts without issue.
With the port options, i get this error:

```
  FATA[0000] Error response from daemon: Cannot start container 7fff4649fe0462cae927c4c0ea340111ab99c73c1be507394b8d2be665f0e30a:  (exit status 1) 
```
My docker info:
```
Containers: 1
Images: 31
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
Execution Driver: native-0.2
Kernel Version: 3.11.0-26-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 2
Total Memory: 1.954 GiB
Name: node-docker-hpcloud-pts-88
ID: WK6Y:VEBU:S2ZU:DF5P:L5DL:2RX6:G46X:OAEY:WCKB:7NBN:HGBN:LDFW
WARNING: No swap limit support
```
uname -a output:

```
Linux node-docker-hpcloud-pts-88 3.11.0-26-generic #45~precise1-Ubuntu SMP Tue Jul 15 04:02:35 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Any ideas on how i can debug this or get more meaningful output for what might be going on?   I don't see that there is anything listening on port 5000, and everything else looks normal.

**Comment by wenlock** [comment]
my docker version:
```
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by mko-x** [comment]
+1

**Comment by dmp42** [comment]
Can you copy the docker daemon logs? preferably using debug (eg: start the docker daemon using `docker -d -D`)

**Comment by wenlock** [comment]
awesome, that added some more debugging, found the log in /var/log/upstart/docker.log

I wasn't able to reproduce it after a fresh re-build of our system, but i suspect the issue was with a bad docker pull.   I can no longer reproduce this issue on my systems.  Closing.
