### ISSUE TITLE
The "Set a tag for a specified image id" is not working

### ISSUE THREAD

**Issue by paturuv** [docker/docker-registry#935]
Hi -

I am trying to create a tag on the private docker registry, using the docker registry API, the call fails with 400 BAD REQUEST.

Could someone throw some light on this, if I am in dark..

Thanks

**Comment by dmp42** [comment]
Can you copy the exact request you are doing, including all parameters and headers?

**Comment by paturuv** [comment]
It is a PUT request.
http://registry-host:port/v1/repositories/namespace/repository:port/tags/v1.0

Thanks
Venkat

**Comment by paturuv** [comment]
It is a PUT request through spring rest template

http://<<docker-registry-host:port>>/v1/repositories/<<namespace(Image Name)>>/<<repositoryname (docker-registry-hostname:port)>>/tags/<<version>>/

Note:strings included within <<>> are specific values that I have provided

Please let me know if you see an issue

**Comment by dmp42** [comment]
Please provide the exact arguments you used.
Likely your repository name is not valid.

**Comment by paturuv** [comment]
It is a PUT request using spring rest template with 3 parameters
Param:1 : ImageName (abc/pqr_base) 
Param:2: RepositoryName (docker-registry-host:port)
 Param-3: newTag

http://<<docker-registry-host:port>>/v1/repositories/<<ImageName>>/<<repositoryName (registry-host:port)>>/tags/<<newTag>>/

Please let me know if you see issue in the above format / parameters

**Comment by dmp42** [comment]
Repository names are only allowed to contain: [a-z0-9-_.]
