### ISSUE TITLE
Unable to find image after pushing to private registry

### ISSUE THREAD

**Issue by ngpestelos** [docker/docker-registry#946]
We've been noticing cases where an image previously pushed to a private registry goes missing (i.e., `docker pull` reports `Unable to find image`). A workaround would be to push to the private registry again before pulling.

Has anyone else encountered this problem?

**Comment by dmp42** [comment]
Nope...
In such cases, have you checked the storage? is the image still physically there?

**Comment by ngpestelos** [comment]
I would like to take a closer look, but I'm not familiar with how docker-registry stores its images. Can you tell me which directory to look for?

**Comment by dmp42** [comment]
It's in your storage_path configuration var. Probably under `/registry/`

**Comment by ngpestelos** [comment]
We're using local storage in one of our machines and it's setup to use `/tmp/registry`. My theory is that the images are flushed when the machine is rebooted.

Thank you very much :+1:
