### ISSUE TITLE
table of content links does not render correctly in the repository overview

### ISSUE THREAD

**Issue by bgruening** [docker/docker-registry#949]
For example the table of contents in https://registry.hub.docker.com/u/bgruening/galaxy-blast/ does not render nicely. You get something like the following:
```
 *   [Installed tools](#installed-tools)
 *   [Usage](#usage)
 *   [Users & Passwords](#user–passowrds)
 *   [Reproducibility of your search results](#reproducibility-of-your-search-results)
 *   [Using large external BLAST databases](#using-large-external-blast-databases)
 *   [Requirements](#requirements)
 *   [Restarting Galaxy](#restarting-galaxy)
 *   [History](#history)
 *   [Support & Bug Reports](#support–bug-reports)
 *   [Licence (MIT)](#license-mit)
```
To quote from https://docs.docker.com/docker-hub/official_repos/:
```
A long description
Include a comprehensive description of your image (in Markdown format, GitHub flavor preferred).
```

Github is rendering it correct: https://github.com/bgruening/docker-galaxy-blast

Link to original bug report: https://github.com/bgruening/docker-galaxy-blast/issues/2

**Comment by WhisperingChaos** [comment]
Thanks for reporting this issue!  I too am experiencing it.

**Comment by dmp42** [comment]
Hi, this is a hub issue.

This here is the open-source registry bug tracker, that does not provide this feature.

Can you report this directly to docker support instead?

https://support.docker.com

Thanks.
