### ISSUE TITLE
docker search return unexpected 404 error

### ISSUE THREAD

**Issue by tdoan1971** [docker/docker-registry#951]
I run the docker private registry on local mode with endpoint set sqlalchemy.
The pull/push works well: ex: docker pull mylocalregistry:5000/base/rhel6.5:v1

However when I run "docker search mylocalregistry:5000/base". It returns "... unexpected 404"
What is the issue?

**Comment by dmp42** [comment]
Can you copy:

 * your registry version
 * your registry configuration
 * your registry launch command

**Comment by tdoan1971** [comment]
Hi dmp42,
- I use the docker-registry-0.9.0-1.el6.noarch rpm from EPEL repository
- I use the default configuration in /etc/docker-register.yml file which uses dev flavor by default
- I launch the registry by "service docker-registry start" commnad

Thanks,

**Comment by dmp42** [comment]
Can you `curl -iv https://mylocalregistry:5000/v1/search?q=base`?

**Comment by tdoan1971** [comment]
Hi Olivier,
I am not near the system now to try the curl command. However I have the flag "--insecure-registry mylocalregistry:5000" on the remote Docker daemon so that it pulls/pushes successfully without user authentication.

**Comment by dmp42** [comment]
My point is: I don't think the search is enabled on your registry - that curl command would make sure about that.

**Comment by tdoan1971** [comment]
Hi Olivier,

So, how to enable the search for the registry if the curl command is false?

Thanks,

Truong Doan
----------------------------------
DISA-EE322 - Perf Analysis & M&S
Room: A5D58G
301-225-7335
"Everything happens for a reason!"
----------------------------------


-----Original Message-----

**Comment by dmp42** [comment]
*If* the search endpoint is not enabled, make sure what configuration you are actually using and/or that the search backend settings is actually set.

**Comment by tdoan1971** [comment]
The problem solved. It turns out that the docker-registry conf file at /etc/sysconfig point to the local flavor which does not have the endpoint flag set. Chage it to the dev flavor to solve the problem.
