### ISSUE TITLE
Missing support for tables in Markdown

### ISSUE THREAD

**Issue by zaporylie** [docker/docker-registry#965]
Unfortunately README.md file containing tables won't be rendered correctly. That feature is really important in Automated Builds workflow.

More about tables in markdown cheetsheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by dmp42** [comment]
This is a hub feature (this here is just the open-source registry).
Please report your request to https://support.docker.com 

Thanks.
