### ISSUE TITLE
Push fails with EOF error

### ISSUE THREAD

**Issue by seraphyong** [docker/docker-registry#993]
docker -d --insecure-registry 192.168.4.77:5000
then  docker run -d -v /root/registry/:/tmp/registry -p 5000:5000 registry
then  docker pull 192.168.4.77:5000/msf
but:
   The push refers to a repository [192.168.4.77:5000/msf] (len: 1)
   Sending image list
   Pushing repository 192.168.4.77:5000/msf (1 tags)
   511136ea3c5a: Pushing [==================================================>] 1.024 kB/1.024 kB
   FATA[0126] Failed to upload layer: Put http://192.168.4.77:5000/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/layer: EOF
and docker deamon show:
   INFO[1083] +job push(192.168.4.77:5000/msf)
   INFO[1083] +job resolve_repository(192.168.4.77:5000/msf)
   INFO[1083] -job resolve_repository(192.168.4.77:5000/msf) = OK (0)
   ERRO[1087] Error in LookupRemoteImage: HTTP code 400
   ERRO[1087] Error in LookupRemoteImage: HTTP code 404
   ERRO[1087] Error in LookupRemoteImage: HTTP code 404
   Failed to upload layer: Put http://192.168.4.77:5000/v1/images/511136ea3c5a64f26                                                                4b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/layer: EOF
I want to konw what's wrrong!

**Comment by dmp42** [comment]
Please provide:

 * docker info
 * docker version
 * command line you used to install and launch your docker-registry
 * your docker-registry configuration

**Comment by seraphyong** [comment]
@dmp42 
I have resolved this question,because I didn't run the image whta I want push.
But also thank you too.
