### ISSUE TITLE
Simultaneous push of two images with the same name but different tag results in an error

### ISSUE THREAD

**Issue by montgomery1944** [docker/docker-registry#994]
The exact message we are getting is:
"Error response from daemon: push image_name is already in progress".

The reason we are pushing two images at the same time with different tags is because we use docker registry to keep our images built by Jenkins, which can of course build different branches of our project at the same time.

Is this issue going to be fixed in the old version of registry?
Is this issue fixed in the registry 2.0?

**Comment by dmp42** [comment]
Hi @montgomery1944 

IMO this is a docker engine issue (not registry).
Nevertheless, I would be happy to investigate.

I think that should work with a registry2. If it's not, that should be fixed.

**Comment by montgomery1944** [comment]
@dmp42, is there any update on this issue?

**Comment by dmp42** [comment]
@montgomery1944 have you tried registry:2 ?
cc @stevvooe

**Comment by stevvooe** [comment]
@montgomery1944 This is a daemon issue. Please file in github.com/docker/docker.
