### ISSUE TITLE
Pushes to Docker Hub suddenly started failing for authentication problem

### ISSUE THREAD

**Issue by pbecotte** [docker/docker-registry#995]
I have a jenkins job that runs 
docker login
docker build
docker push

Today, it started failing every time.  The daemon output suggests it is a failure to login... immediately after sucessfully logging in :)  I logged in and ran it interactively and got the same result, it kept prompting me to login and then failing.  FYI, this job is executed INSIDE of a docker container jpetazzo/dind (v 1.6.0)

Please login prior to push:
Username (pbecotte): pbecotte
INFO[0302] POST /v1.18/auth                             
INFO[0302] +job auth()                                  
INFO[0302] +job resolve_index(https://index.docker.io/v1/) 
INFO[0302] -job resolve_index(https://index.docker.io/v1/) = OK (0) 
INFO[0302] successful registry login for endpoint https://index.docker.io/v1/: Login Succeeded 
INFO[0302] -job auth() = OK (0)                         
WARNING: login credentials saved in /root/.dockercfg.
Login Succeeded
INFO[0302] POST /v1.18/images/bamx/fluentd/push?tag=f36878da9596027d9b77b68693ab321e1ab9131d 
INFO[0302] +job push(bamx/fluentd)                      
INFO[0302] +job resolve_repository(bamx/fluentd)        
INFO[0302] -job resolve_repository(bamx/fluentd) = OK (0) 
The push refers to a repository [bamx/fluentd] (len: 1)
025e15ace0fb: Image push failed 
Error pushing to registry: Authentication is required.
INFO[0302] -job push(bamx/fluentd) = ERR (1)  

################

The behavior on the pull command is even wierder... the login fails and then it pulls anyway...

INFO[0151] POST /v1.18/images/create?fromImage=bamx%2Ffluentd%3Alatest 
INFO[0151] +job pull(bamx/fluentd, latest)              
INFO[0151] +job resolve_repository(bamx/fluentd)        
INFO[0151] -job resolve_repository(bamx/fluentd) = OK (0) 
ERRO[0151] Error from V2 registry: Authentication is required. 
Pulling repository bamx/fluentd
025e15ace0fb: Download complete 
511136ea3c5a: Download complete 
4f903438061c: Download complete 
1265e16d0c28: Download complete 
85ab397841a4: Download complete 
e7f2b26d1aa9: Download complete 
d0036566add8: Download complete 
ebb327a9690a: Download complete 
75ab5759cb5e: Download complete 
7d5dd7f51434: Download complete 
e0746a0402f8: Download complete 
fbaa697652ed: Download complete 
a0e004ac5b07: Download complete 
e1821cd8c79b: Download complete 
38b72ccce517: Download complete 
a16b5ebc7cc5: Download complete 
24e5fbc169f7: Download complete 
ab4227500be7: Download complete 
127c2def46f0: Download complete 
INFO[0172] +job log(pull, bamx/fluentd:latest, )        
Status: Image is up to date for bamx/fluentd:latest
INFO[0172] -job log(pull, bamx/fluentd:latest, ) = OK (0) 
INFO[0172] -job pull(bamx/fluentd, latest) = OK (0) 

###########################

docker info:
Containers: 0
Images: 19
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 2
Total Memory: 3.859 GiB
Name: cb8f2d26cad0
ID: CORI:XMJJ:BDWX:5SQA:CWCT:PTZW:GKTI:G3NL:4MR4:LT6J:G6YG:GJ4H
Username: pbecotte
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

**Comment by dmp42** [comment]
There has been an issue with authentication on the hub.

https://status.docker.com/pages/incident/533c6539221ae15e3f000031/554293d934de855a3800061b

It's fixed now.
Let me know if you still experience issues.

**Comment by pbecotte** [comment]
Nope, looks good.  Thanks for the quick response!

**Comment by lox** [comment]
I'm currently having the same issue.

**Comment by ebaxt** [comment]
Same problem here as well

**Comment by tnlin** [comment]
I got the exactly same problem

**Comment by DexterTheDragon** [comment]
Having this problem using docker 1.7.0

**Comment by newtondev** [comment]
Having the exact same problem.

**Comment by Master244** [comment]
Also having it atm

**Comment by haimari** [comment]
Same issue

**Comment by dmp42** [comment]
Hub problems must be reported to https://support.docker.com

This here is a closed issue.
