### ISSUE TITLE
Error pushing to registry: Authentication is required.

### ISSUE THREAD

**Issue by ronin13** [docker/docker-registry#997]
I am getting this error in docker automated build: https://registry.hub.docker.com/u/ronin/fstools/build_id/59112/code/bjwj8cryp2sc9ruzwhsdzmm/  - though it looks intermittent since a previous build was successful.

I see an older issue marked fixed https://github.com/docker/docker-registry/issues/995 (also noted at https://status.docker.com/pages/incident/533c6539221ae15e3f000031/554293d934de855a3800061b) but it seems like it is happening again but with docker registry automated builds.

**Comment by ventres** [comment]
I am also seeing this error in my automated build repository: https://registry.hub.docker.com/u/foodlogiq/api/build_id/37077/code/bklej8f97kynzupskwfysmq/ 
I will give it some time and try it again to see if I also see intermittent success.

**Comment by benhamner** [comment]
@dmp42 I'm also hitting this error with one of my automated build repositories: https://registry.hub.docker.com/u/kaggle/r/build_id/53243/code/bvep6hoqrvyqyy69zmr2cx8/

**Comment by dmp42** [comment]
Hi @ronin13 @ventres @benhamner 

Automated builds is not the open-source python registry - it's a Hub feature.
I'm sorry to close this, but really there is nothing I can do here - this is definitely a Hub issue, that you should report directly to the support over here: https://support.docker.com
